services:
  - type: web
    name: chatwoot
    env: ruby
    region: oregon
    plan: free
    buildCommand: bundle install && yarn install && bundle exec rails assets:precompile
    startCommand: bundle exec rails s -b 0.0.0.0 -p $PORT
    envVars:
      - key: RAILS_ENV
        value: production
      - key: INSTALLATION_ENV
        value: render
      - key: FRONTEND_URL
        value: https://chatwoot.onrender.com
      - key: SECRET_KEY_BASE
        fromDatabase: false
      - key: DISABLE_EMAIL_VERIFICATION
        value: "true"
      - key: DEFAULT_LOCALE
        value: es
